### PR TITLE
Factor out data producing functions

### PR DESCRIPTION
**Pull request by perrin4869**
Hi, I made small changes to the converting functions to separate the data creating part from the part that writes the data to the files, and checked that the tests passed. This will help me use this repo to write a gulp plugin. Thanks!

### CODE REVIEW

**Comment by jamuhl** [comment]
will check and merge this asap.

**Comment by perrin4869** [comment]
I thought it would be helpful if I made the changes I submitted more clear. I changed this bit of code inside `i18nextToGettext`:

```javascript
        self.flattenI18nextJSON(source, options, function(err, flat) {
            self.parseGettext(domain, flat, options, function(err, gt) {

                var data = path.extname(target) === '.po' ? gt.compilePO(domain) : gt.compileMO(domain);

                self.writeFile(target, data, options, callback);
            });
        });
```
into:

```javascript
self.i18nextToGettextData(domain, source, path.extname(target), options, function(err, data) {
            self.writeFile(target, data, options, callback);
});
```

where I defined a new function, `i18nextToGettextData`:

```javascript
i18nextToGettextData: function(domain, source, target, options, callback) {
        if (typeof options === 'function') {
            callback = options;
            options = {};
        }

        var self = this;

        self.flattenI18nextJSON(source, options, function(err, flat) {
            self.parseGettext(domain, flat, options, function(err, gt) {
                var data = path.extname(target) === '.po' ? gt.compilePO(domain) : gt.compileMO(domain);
                callback(err, data);
            });
        });
}
```

The purpose of this change is to be able to use `i18nextToGettextData` on its own outside of the binary (in my case, as a gulp plugin). A similar change has been made to the `gettextToI18next` by adding a `gettextToI18nextData`.

**Comment by jamuhl** [comment]
https://www.npmjs.com/package/i18next-conv

v0.1.5 deployed on npm.

**Comment by jamuhl** [comment]
would be nice if you keep me uptodate on the gulp plugin...

**Comment by perrin4869** [comment]
Always been the plan :)
https://www.npmjs.com/package/gulp-i18next-conv
Need to write up a readme, examples, tests, and maybe small improvements. Let me know how I can share it in the main i18next repo if you're interested! Also, I'd like to help out with i18next version 2.0.0, I've taken a liking to the project, tell me how I can help! I do have a few improvements in mind too

**Comment by jamuhl** [comment]
if you want to add your repo to i18next organisation account i can add you there for transfer and later add needed rights to access it.

upcoming v2 is right now wip: https://github.com/jamuhl/i18next-playground

help there is more then welcome. right now i want to add the first draft for loading mechanism, so main parts are there and working. (plus adding some readme, with goals and basic structure of new project)

right now it would be great if you could share your ideas and have a look at new code base:

-> gulp tdd (will run new tests)
-> gulp test_compat (will run current state of compatibility to v1.x.x API and JSON Format)

(one of the biggest things on the list is generating some documentation like i18next.com - but want that to be generated out from markdown files (using https://github.com/millermedeiros/mdoc or something similar) for easier contribution.)

**Comment by perrin4869** [comment]
Will be looking at it later for sure then! Thanks!
BTW, how is the Mongoose team generating their documentation? I find it rather useful, they even have a button where you can look at the source for function and object definitions and stuff

**Comment by jamuhl** [comment]
looks like they take a lot of effort to build that: https://github.com/Automattic/mongoose/tree/gh-2462

**Pull request merged**
