### PR TITLE
Make options and callback arguments optional

### LINKED ISSUE #39: Make options optional
Currently the options argument is required for all functions.
```js
if (!options.quiet) console.log(('\n    --> reading file from: ' + sou
            ^
TypeError: Cannot read property 'quiet' of undefined
```

The library should check if it's `undefined` and fallback to empty object.

### PR DESCRIPTION
**Pull request by megapctr**
Closes #39

### CODE REVIEW

**Comment by megapctr** [comment]
There are two small problems with my test for checking if the `options` argument is optional:
  1. There are some lines being printed when running the tests, because I can't pass `quiet: true` to this test
  2. There's an untracked file after running the tests, because I can't pass a callback to delete it

And ideas for fixing them?

**Comment by jamuhl** [comment]
there was a big rewrite: https://github.com/i18next/i18next-gettext-converter/pull/41

can you make this PR free of conflicts again...sorry for the fuss.

**Comment by megapctr** [comment]
done

**Comment by jamuhl** [comment]
v2.4.0 published...thanks for fixing this.

**Pull request merged**
