### PR TITLE
Split with Whitespace in reference

### PR DESCRIPTION
**Pull request by safwanrahman**
#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [ ] run tests `npm run test`
- [ ] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

**Comment by jamuhl** [comment]
Can you please add more details. What was broken - what tries this PR to fix? And if possible add a test case to avoid future regression. Thank you.

**Comment by safwanrahman** [comment]
@jamuhl My `.po` file has the reference comment in the same line like following:
```po
#: common##cancel error##cancel
msgid "Cancel"
msgstr "Annuleer"
```

But while converting from `po` to `json`, the converter could not detect the double references in the same line, so it creates a key `cancel error` like following:
```
{
   "common":{
      "cancel error":{
         "cancel":"Annuleer"
      }
   }
}
```

Regarding test case, I have not much experience with js, so can you let me know where to put the test case?

**Comment by jamuhl** [comment]
tests come here: https://github.com/i18next/i18next-gettext-converter/blob/master/test/index.js

**Comment by safwanrahman** [comment]
@jamuhl Thanks. It seems overchallenging for me to write tests in the test suit. Can you help me a bit more by providing a similar test case?

**Comment by jamuhl** [comment]
it's like: https://github.com/i18next/i18next-gettext-converter/blob/master/test/index.js#L115

which compares input testfile https://github.com/i18next/i18next-gettext-converter/blob/master/test/_testfiles/en/translation.utf8.po with output testfile https://github.com/i18next/i18next-gettext-converter/blob/master/test/_testfiles/en/translation.utf8.json

**Comment by perrin4869** [comment]
This PR doesn't target this repo anymore... should consider targeting `gettext-converter` if you're still interested

**Pull request closed without merging**
