### PR TITLE
airbnb eslint config

### PR DESCRIPTION
**Pull request by perrin4869**
This is quite a big one. Refactored everything to pass the airbnb eslint config, bar a few rules I turned off here and there. There were some tricky parts with the plurals section, but I think I got those right.

### CODE REVIEW

**Comment by jamuhl** [comment]
gave you full rights on the repo...do you have a npm account...will give you publish rights too

**Comment by perrin4869** [comment]
Cool, thanks!

**Comment by perrin4869** [comment]
My npm username is the same as here, `perrin4869` :)

**Comment by jamuhl** [comment]
just added you as npm module owner...happy publishing ;)

**Comment by perrin4869** [comment]
thanks, will try to make a major release this week!

**Pull request merged**
